server:
  port: 8090
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: emvproject
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=emvprojectdb;schema=dbo;encrypt=true;trustServerCertificate=true
    username: sa
    password: StrongP@ssw0rd!
    #    url: Server=WIN-2OR5H1CA80E\\MSSQLSERVER01;Database=bd_adds103;Trusted_Connection=True;
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
          time_zone: UTC
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: validate
    open-in-view: true
    show-sql: true
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    com.innowise.pathology3d: info
    root: info
  file:
    name: logs/emvproject.log
  pattern:
    dateformat: dd-MM-yyyy HH:mm:ss.SSS, Europe/Minsk
  logback:
    rollingpolicy:
      max-history: 30
      max-file-size: 10MB
      file-name-pattern: logs/archived/telcard.%d{dd-MM-yyyy}.%i.log

jwt:
  key: DEV-JWT-SIGN-KEY_DEV-JWT-SIGN-KEY_DEV-JWT-SIGN-KEY_DEV-JWT-SIGN-KEY
  token-header: Authorization
  token-prefix: "Bearer "
  token-issuer: emvproject

token-ttl:
  access: 3600
  refresh: 86400