CREATE TABLE projects
(
    id                                                              INT          NOT NULL IDENTITY(1,1) UNIQUE,
    name                                                            VARCHAR(100) NOT NULL UNIQUE,
    correct_code_implementation_status                              VARCHAR(100) NOT NULL DEFAULT 'N/A',
    correct_code_implementation_description                         TEXT,
    correct_mobile_site_tracking_status                             VARCHAR(100) NOT NULL DEFAULT 'N/A',
    correct_mobile_site_tracking_description                        TEXT,
    code_singularity_status                                         VARCHAR(100) NOT NULL DEFAULT 'N/A',
    code_singularity_description                                    TEXT,
    correct_single_page_application_tracking_status                 VARCHAR(100) NOT NULL DEFAULT 'N/A',
    correct_single_page_application_tracking_description            TEXT,
    cross_domain_tracking_configuration_status                      VARCHAR(100) NOT NULL DEFAULT 'N/A',
    cross_domain_tracking_configuration_description                 TEXT,
    self_referrals_status                                           VARCHAR(100) NOT NULL DEFAULT 'N/A',
    self_referrals_description                                      TEXT,
    payment_process_referrals_status                                VARCHAR(100) NOT NULL DEFAULT 'N/A',
    payment_process_referrals_description                           TEXT,
    utm_tagging_status                                              VARCHAR(100) NOT NULL DEFAULT 'N/A',
    utm_tagging_description                                         TEXT,
    pages_404_error_tracking_status                                 VARCHAR(100) NOT NULL DEFAULT 'N/A',
    pages_404_error_tracking_description                            TEXT,
    main_domain_in_list_unwanted_referrals_status                   VARCHAR(100) NOT NULL DEFAULT 'N/A',
    main_domain_in_list_unwanted_referrals_description              TEXT,
    session_timeout_status                                          VARCHAR(100) NOT NULL DEFAULT 'N/A',
    session_timeout_description                                     TEXT,
    lookback_window_status                                          VARCHAR(100) NOT NULL DEFAULT 'N/A',
    lookback_window_description                                     TEXT,
    user_and_event_data_retention_status                            VARCHAR(100) NOT NULL DEFAULT 'N/A',
    user_and_event_data_retention_description                       TEXT,
    ecommerce_data_accuracy_status                                  VARCHAR(100) NOT NULL DEFAULT 'N/A',
    ecommerce_data_accuracy_description                             TEXT,
    traffic_to_not_set_landing_page_status                          VARCHAR(100) NOT NULL DEFAULT 'N/A',
    traffic_to_not_set_landing_page_description                     TEXT,
    currency_status                                                 VARCHAR(100) NOT NULL DEFAULT 'N/A',
    currency_description                                            TEXT,
    define_internal_traffic_status                                  VARCHAR(100) NOT NULL DEFAULT 'N/A',
    define_internal_traffic_description                             TEXT,
    industry_category_status                                        VARCHAR(100) NOT NULL DEFAULT 'N/A',
    industry_category_description                                   TEXT,
    reporting_time_zone_status                                      VARCHAR(100) NOT NULL DEFAULT 'N/A',
    reporting_time_zone_description                                 TEXT,
    event_tracking_status                                           VARCHAR(100) NOT NULL DEFAULT 'N/A',
    event_tracking_description                                      TEXT,
    conversion_tracking_status                                      VARCHAR(100) NOT NULL DEFAULT 'N/A',
    conversion_tracking_description                                 TEXT,
    standard_purchase_ecommerce_tracking_implementation_status      VARCHAR(100) NOT NULL DEFAULT 'N/A',
    standard_purchase_ecommerce_tracking_implementation_description TEXT,
    enhanced_measurement_status                                     VARCHAR(100) NOT NULL DEFAULT 'N/A',
    enhanced_measurement_description                                TEXT,
    user_id_tracking_implementation_status                          VARCHAR(100) NOT NULL DEFAULT 'N/A',
    user_id_tracking_implementation_description                     TEXT,
    enhnanced_ecommerce_tracking_status                             VARCHAR(100) NOT NULL DEFAULT 'N/A',
    enhnanced_ecommerce_tracking_description                        TEXT,
    custom_dimensions_and_metrics_tracking_status                   VARCHAR(100) NOT NULL DEFAULT 'N/A',
    custom_dimensions_and_metrics_tracking_description              TEXT,
    granular_location_and_device_data_collection_status             VARCHAR(100) NOT NULL DEFAULT 'N/A',
    granular_location_and_device_data_collection_description        TEXT,
    advanced_settings_to_allow_for_ads_personalization_status       VARCHAR(100) NOT NULL DEFAULT 'N/A',
    advanced_settings_to_allow_for_ads_personalization_description  TEXT,
    property_name_status                                            VARCHAR(100) NOT NULL DEFAULT 'N/A',
    property_name_description                                       TEXT,
    stream_name_status                                              VARCHAR(100) NOT NULL DEFAULT 'N/A',
    stream_name_description                                         TEXT,
    event_tracking_taxonomy_status                                  VARCHAR(100) NOT NULL DEFAULT 'N/A',
    event_tracking_taxonomy_description                             TEXT,
    google_bigquery_linking_status                                  VARCHAR(100) NOT NULL DEFAULT 'N/A',
    google_bigquery_linking_description                             TEXT,
    library_status                                                  VARCHAR(100) NOT NULL DEFAULT 'N/A',
    library_description                                             TEXT,
    google_ads_linking_status                                       VARCHAR(100) NOT NULL DEFAULT 'N/A',
    google_ads_linking_description                                  TEXT,
    google_search_console_linking_status                            VARCHAR(100) NOT NULL DEFAULT 'N/A',
    google_search_console_linking_description                       TEXT,
    google_merchant_center_linking_status                           VARCHAR(100) NOT NULL DEFAULT 'N/A',
    google_merchant_center_linking_description                      TEXT,
    display_and_video_360_linking_status                            VARCHAR(100) NOT NULL DEFAULT 'N/A',
    display_and_video_360_linking_description                       TEXT,
    data_import_status                                              VARCHAR(100) NOT NULL DEFAULT 'N/A',
    data_import_description                                         TEXT,
    ad_manager_linking_status                                       VARCHAR(100) NOT NULL DEFAULT 'N/A',
    ad_manager_linking_description                                  TEXT,
    search_ads_360_linking_status                                   VARCHAR(100) NOT NULL DEFAULT 'N/A',
    search_ads_360_linking_description                              TEXT,
    google_signals_data_collection_status                           VARCHAR(100) NOT NULL DEFAULT 'N/A',
    google_signals_data_collection_description                      TEXT,
    reporting_attribution_model_status                              VARCHAR(100) NOT NULL DEFAULT 'N/A',
    reporting_attribution_model_description                         TEXT,
    reporting_attribution_identity_status                           VARCHAR(100) NOT NULL DEFAULT 'N/A',
    reporting_attribution_identity_description                      TEXT,
    server_side_tracking_implementation_status                      VARCHAR(100) NOT NULL DEFAULT 'N/A',
    server_side_tracking_implementation_description                 TEXT,
    consent_mode_status                                             VARCHAR(100) NOT NULL DEFAULT 'N/A',
    consent_mode_description                                        TEXT,
    pii_data_not_collection_status                                  VARCHAR(100) NOT NULL DEFAULT 'N/A',
    pii_data_not_collection_description                             TEXT,
    PRIMARY KEY (id)
);

INSERT INTO projects (name)
VALUES ('VIDEN'),
       ('GOOGLE');